// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOHXqSMcML7L_XwS1zfbcY7bEq-NiriY0',
    appId: '1:1004314517942:web:62cc413a37b0d306286117',
    messagingSenderId: '1004314517942',
    projectId: 'quickcab-project',
    authDomain: 'quickcab-project.firebaseapp.com',
    storageBucket: 'quickcab-project.firebasestorage.app',
    measurementId: 'G-S2998GCBGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVHZzABwA19oUptRBwq35yzXGn3XxXE98',
    appId: '1:1004314517942:android:9637f882c5515bca286117',
    messagingSenderId: '1004314517942',
    projectId: 'quickcab-project',
    storageBucket: 'quickcab-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBt8qf3DIOsSbofog_uxe6hW0jc5RBus',
    appId: '1:1004314517942:ios:9e7156c53dc68d3e286117',
    messagingSenderId: '1004314517942',
    projectId: 'quickcab-project',
    storageBucket: 'quickcab-project.firebasestorage.app',
    iosBundleId: 'com.example.quickcabDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBt8qf3DIOsSbofog_uxe6hW0jc5RBus',
    appId: '1:1004314517942:ios:9e7156c53dc68d3e286117',
    messagingSenderId: '1004314517942',
    projectId: 'quickcab-project',
    storageBucket: 'quickcab-project.firebasestorage.app',
    iosBundleId: 'com.example.quickcabDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOHXqSMcML7L_XwS1zfbcY7bEq-NiriY0',
    appId: '1:1004314517942:web:4dcb099f42fb3682286117',
    messagingSenderId: '1004314517942',
    projectId: 'quickcab-project',
    authDomain: 'quickcab-project.firebaseapp.com',
    storageBucket: 'quickcab-project.firebasestorage.app',
    measurementId: 'G-67R1ZX6JM8',
  );
}
